#!/bin/sh

set -eu

lib=$(dirname "$0")/../jagen-lib
usr=$(dirname "$0")
products="ast-sigma-firmware ast-hi-linux genivi"

setup_product() {
    local product="${1:-}"; shift
    rm -rf "$product"
    echo "setup $product"
    (
        mkdir -p "$product"; cd "$product"
        "$jagen_dir/init" -i "$usr" "$lib" "$@"
        cp -a "build/build.ninja" "build/build.ninja.orig"
        cp -a "include" "include.orig"
        . ./env.sh
        jagen list packages > list.packages.txt
        cp -a list.packages.txt list.packages.txt.orig
    )
}

refresh_product() {
    (
        cd $1
        . ./env.sh
        jagen refresh
    )
}

check_product() {
    local name="$1"
    (
        printf "===== %-20s =====\n" "$name"
        cd "$name"
        diff -u build/build.ninja.orig build/build.ninja || true
        diff -u include.orig include || true
        if [ -f list.packages.txt.orig ] && [ -f list.packages.txt ]; then
            diff -u list.packages.txt.orig list.packages.txt || true
        fi
    )
}

case $1 in
    setup)
        jagen_dir="$2"
        setup_product ast-sigma-firmware vendor/ast sdk/sigma product/ast-sigma-firmware
        setup_product ast-hi-linux vendor/ast sdk/hi-linux product/ast-hi-linux
        setup_product genivi vendor/genivi
        ;;
    refresh)
        for product in $products; do
            refresh_product "$product"
        done ;;
    check)
        for product in $products; do
            check_product "$product"
        done ;;
esac
